[tool.poetry]
name = "lab2"
version = "0.1.0"
description = "Lab 2: Data Models and Inference"
authors = ["Jorge Sandoval <sandoval@berkeley.edu>"]
readme = "README.md"
packages = [{ include = "src" }]

[tool.poetry.dependencies]
python = "^3.10"  # Change this to match the autograder's expectation
fastapi = "0.95.1"  # Update to the correct version expected by the autograder
scikit-learn = "1.5.2"
joblib = "1.4.2"

[tool.poetry.dev-dependencies]
pytest = "^7.4.4"
pytest-cov = "^4.0.0"
ruff = "^0.1.15"  # Update to the correct version expected by the autograder

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
