[tool.poetry]
name = "lab2"
version = "0.1.0"
description = "Lab 2: Data Models and Inference"
authors = ["Jorge Sandoval <sandoval@berkeley.edu>"]
readme = "README.md"
packages = [{ include = "src" }]

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "0.95.2"
scikit-learn = "1.5.2"
joblib = "1.4.2"
uvicorn = "^0.23.0"

[tool.poetry.dev-dependencies]
pytest = "7.4.4"  # match exact version
pytest-cov = "^4.0.0"
ruff = "0.1.15"   # match exact version

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
