[tool.poetry]
name = "lab2"
version = "0.1.0"
description = "Lab 2: Data Models and Inference"
authors = ["Jorge Sandoval <sandoval@berkeley.edu>"]
readme = "README.md"
packages = [{ include = "src" }]

[tool.poetry.dependencies]
python = "^3.11"  # Allow any version of Python 3.11
fastapi = "^0.95"  # Allow any patch version >= 0.95, in case a higher one is required
scikit-learn = "1.5.2"
joblib = "1.4.2"

[tool.poetry.dev-dependencies]
pytest = "^7.4"  # Use a range for pytest to accommodate more minor versions
pytest-cov = "^4.0.0"
ruff = "^0.1"  # Use a broad range to cover multiple versions of ruff

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
