[tool.poetry]
name = "lab2"
version = "0.1.0"
description = "Lab 2: Data Models and Inference"
authors = ["Jorge Sandoval <sandoval@berkeley.edu>"]
readme = "README.md"
packages = [{ include = "src" }]

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "0.94.1"  # Adjust based on version compatibility with Pydantic 1.x
joblib = "^1.4"
scikit-learn = "^1.5"
pydantic = "1.10.8"

[tool.poetry.dev-dependencies]
pytest = "7.4.2"  # Adjust the version based on your environment
ruff = "0.6.2"    # Use the version specified by the grader
httpx = "^0.27.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
